### PR TITLE
Feature/openvr

### PR DESCRIPTION
**Pull request by eriksunden**
You can now use OpenVR as projection source and for viewing an OpenSpace scene in an HMD, specially an Oculus Rift or an HTC Vive. Only HMD tracking and rendering is currently considered, no controller. You can compile with this functionality enabled, but they will be no setup/overhead if a window hasn't specified OpenVR in the currently utilized sgct config file.

### CODE REVIEW

**Comment by EricMyers47** [comment]
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenVR (missing: OPENVR_INCLUDE_DIR OPENVR_LIBRARY)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  ext/sgct/cmake/modules/FindOpenVR.cmake:105 (find_package_handle_standard_args)
  apps/OpenSpace/CMakeLists.txt:38 (find_package)
  support/cmake/support_macros.cmake:213 (include)
  CMakeLists.txt:50 (handle_applications)
```

So it looks like I'll need to build/install OpenVR first, and we would want to put the instructions to do so in the wiki for all platforms.

**Comment by EricMyers47** [comment]
Will we need a headset to test this, or is there a way to know it's working without a headset?

**Comment by eriksunden** [comment]
Just checkout https://github.com/ValveSoftware/openvr and set the environmental variable "OPENVR_ROOT" to the checkout directory. Yes, this should be added to a wiki.

And yes, an OpenVR compatible HMD is needed to make sure it's working.

**Comment by EricMyers47** [comment]
Great.  Thank you.  I'm excited to see this in action.

I want to get straight how best to include OpenVR in the build.  Should it be built as an extension to OpenSpace (as we do with Ghoul or SGCT) or as an extension to SGCT?   I'm guessing to OpenSpace, but correct me if you intend it for SGCT.   Thanks.

**Comment by EricMyers47** [comment]
Another question, based on the README notes.  Do we also need to get another library from Steam, or is this complete as it is?

**Comment by EricMyers47** [comment]
Okay, I made progress on testing this on my Mac by cloning the OpenVR repo and pointing CMake to it.   But when I go to build I get 
```
In file included from /Users/myers/Desktop/OpenSpace/develop/OpenSpace/ext/sgct/additional_includes/openvr/SGCTOpenVR.cpp:8:
In file included from /Users/myers/Desktop/OpenSpace/develop/OpenSpace/ext/sgct/additional_includes/openvr/SGCTOpenVR.h:16:
In file included from /Users/myers/Desktop/OpenSpace/develop/OpenSpace/ext/sgct/include/sgct/ogl_headers.h:21:
/usr/local/include/GL/glew.h:85:2: error: gl.h included before glew.h
#error gl.h included before glew.h
```

**Comment by eriksunden** [comment]
Hopefully made a fix for your error now. I'm compiling SGCT on both Windows and Mac (so made sure that OpenVR in SGCT worked on both platforms), but OpenSpace only on Windows at the moment. Also, I have not tried and HMD/OpenVR example on Mac either, as most Macs (including my Macbook) are not really suited for VR.

**Comment by eriksunden** [comment]
I did now setup OpenSpace build on my Mac and configured it with OpenVR. I noticed the compile error remained and that you previously had encounter it in the ghoul library, so used the same Apple specific definition fix for this error.

**Comment by EricMyers47** [comment]
This now builds on all 3 platforms in Jenkins with OPENSPACE_OPENVR_SUPPORT unchecked, and that should be enough to pull it into the develop branch, but I want to test that it runs correctly too.  I was able to build it on Mac with OpenVR support on, and that builds, but fails at execution due to missing dynamic library (not unexpected).   I want to try that on Windows too.     How can we get that dynamic library?

**Comment by EricMyers47** [comment]
Unfortunately there's a problem when I build this on my Mac with OPENSPACE_OPENVR_SUPPORT off (unchecked).   It still is looking for libopenvr_api.dylib
```
Erics-MBP:Debug> ./OpenSpace 
dyld: Library not loaded: @loader_path/libopenvr_api.dylib
  Referenced from: /Users/myers/Desktop/OpenSpace/develop/OpenSpace/bin/openspace/Debug/./OpenSpace
  Reason: image not found
Trace/BPT trap
```
I can clear the problem if I clear the CMake cache between builds, but is there a way to get it to build and work simply by unchecking that box?

**Comment by eriksunden** [comment]
Easy peasy, issue should be fixed in latest commit.

**Comment by EricMyers47** [comment]
We are getting closer to being able to pull this into the develop branch.  It builds and runs on my Mac with OpenVR support turned off, and you can turn it on and off and CMake does the right thing.  Thank you for that.    Unfortunately while it builds on Windows it crashed for me, but the problem seems to be in the develop branch, not this code.   I'd like to hold off merging until that is fixed.   But we are getting closer...

**Comment by EricMyers47** [comment]
I started a wiki page for OpenVR.    https://github.com/OpenSpace/OpenSpace/wiki/Building-OpenSpace-with-OpenVR-support
Please, anybody, add to it or fix it as best you can.

**Comment by GPayne** [comment]
I added to the OpenVR wiki page, and arranged the main page so that a link to it is listed on the main OpenSpace wiki page (OpenVR wiki URL is now different).

**Pull request merged**
