### PR TITLE
macos compile and build (still needs ring shader const fix)

### PR DESCRIPTION
**Pull request by micahnyc**
macos compile fixes. 
Also Shadow-Mapping identifier fix for debug builds.

### CODE REVIEW

**Comment by micahnyc** [comment]
addresses: #1062 #996

**Comment by alexanderbock** [comment]
Can we inlude the ring shader fix into this as well? @jccosta ?

**Comment by jccosta** [comment]
> Can we inlude the ring shader fix into this as well? @jccosta ?

Yes.

**Comment by micahnyc** [comment]
I just updated this with fixes for the renderable trail. Trails and rings now working on mac. Ready to merge.

**Pull request merged**
