### PR TITLE
SessionRecording and KeyframeRecording cleanup

### PR DESCRIPTION
**Pull request by alexanderbock**
This PR cleans up the SessionRecording (now SessionRecordingHandler) and KeyframeRecording (now KeyframeRecordingHandler) and introduces a new SessionRecording struct that is the timeline for both.  This removes the need for duplicate code in either.  With this change, the KeyframeRecordingHandler also handles script keyframes.

This PR also increases the version number for session recordings, but all previous session recording files should be automatically upconverted without need for user interaction.

This PR needs this UI PR to function: https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/200

Specifically to test:
@GPayne :  To see if Linux generated Session Recording files load on Windows and vice versa
@jockekilby : Does it still do everything you needed?
@engbergandreas : Anything more to simplify or things that are unclear?

### CODE REVIEW

**Comment by GPayne** [comment]
In my windows build attempt, I got the following error:
`static_assert failed: 'Unimplemented overload'`
in sessionrecording.cpp at lines 182 and 232.
(commit a9370ab on Windows 11, x64 RelWithDebInfo build, VisualStudio 2022 17.8.6, CMake 3.26.4)

**Comment by alexanderbock** [comment]
Could you update your Visual Studio version?  I think there might have been a bug fix in a later Visual Studio version.  If it works, we'll need to update the requirement

**Comment by GPayne** [comment]
@alexanderbock  I upgraded Visual Studio to 17.11.3, and it builds and runs successfully. Looks like we'll need to update the VS requirement.

**Comment by alexanderbock** [comment]
Getting a crash with this file:

```
OpenSpace_record/playback01.00A
script 209.064 0 781576828.993  1 openspace.time.setPause(false)
script 209.064 0 781576828.993  1 openspace.time.setDeltaTime(1)
camera 209.246 0.182272 781576829.071 0.69240007779591295 45.32654618349864961 44.90157849672622348 -0.58411580324172974 0.03489570319652557 0.20179392397403717 0.78541082143783569 3.78988647460937500e+02 F ISS
camera 209.425 0.361176 781576829.253 0.69240119932888078 45.32654446806247961 44.90158277594014891 -0.58411586284637451 0.03489585220813751 0.20179393887519836 0.78541076183319092 3.78988616943359375e+02 F ISS
camera 209.611 0.547956 781576829.432 0.69239928748669577 45.32654374200360081 44.90158917836554053 -0.58411586284637451 0.03489589691162109 0.20179395377635956 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 209.81 0.746638 781576829.618 0.69239860666601949 45.32654531226533834 44.90159545676060304 -0.58411586284637451 0.03489573299884796 0.20179399847984314 0.78541082143783569 3.78988586425781250e+02 F ISS
camera 209.98 0.916444 781576829.817 0.69240193884628987 45.32654743831168531 44.90159085157793584 -0.58411592245101929 0.03489577770233154 0.20179396867752075 0.78541082143783569 3.78988586425781250e+02 F ISS
camera 210.177 1.11377 781576829.987 0.69240198276436615 45.32654935285960107 44.90158524078098878 -0.58411598205566406 0.03489568829536438 0.20179395377635956 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 210.364 1.30043 781576830.184 0.69240138530724238 45.32655143538297438 44.90158711868345165 -0.58411592245101929 0.03489550948143005 0.20179401338100433 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 210.536 1.47281 781576830.371 0.69240135458718299 45.32655135820468928 44.90158071847062615 -0.58411592245101929 0.03489552438259125 0.20179402828216553 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 210.728 1.66404 781576830.543 0.69240419761894678 45.32655134998147872 44.90158391246779956 -0.58411592245101929 0.03489562869071960 0.20179398357868195 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 210.908 1.84419 781576830.734 0.69240236966967927 45.32655180718305132 44.90158302843659044 -0.58411598205566406 0.03489583730697632 0.20179396867752075 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 211.097 2.03327 781576830.915 0.69240364826404033 45.32655488622202000 44.90157649547469987 -0.58411598205566406 0.03489564359188080 0.20179398357868195 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 211.288 2.22427 781576831.104 0.69240247728041737 45.32655273287525688 44.90157327294470946 -0.58411604166030884 0.03489552438259125 0.20179399847984314 0.78541070222854614 3.78988616943359375e+02 F ISS
camera 211.464 2.40059 781576831.295 0.69239671900963984 45.32655179093354292 44.90157532314832167 -0.58411598205566406 0.03489542007446289 0.20179399847984314 0.78541076183319092 3.78988616943359375e+02 F ISS
camera 211.66 2.59695 781576831.471 0.69239497794467297 45.32655152009533595 44.90158225169611939 -0.58411592245101929 0.03489556908607483 0.20179399847984314 0.78541082143783569 3.78988586425781250e+02 F ISS
camera 211.84 2.77634 781576831.667 0.69239365614248349 45.32654900077498183 44.90158948262124738 -0.58411592245101929 0.03489553928375244 0.20179402828216553 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 212.017 2.95377 781576831.847 0.69239330400540311 45.32654979140723128 44.90158822708896480 -0.58411586284637451 0.03489543497562408 0.20179396867752075 0.78541082143783569 3.78988586425781250e+02 F ISS
camera 212.207 3.14355 781576832.024 0.69239754015000088 45.32655336664724643 44.90158532481488862 -0.58411586284637451 0.03489556908607483 0.20179396867752075 0.78541076183319092 3.78988586425781250e+02 F ISS
camera 212.392 3.32803 781576832.214 0.69239752660546827 45.32655449487820931 44.90159162566894224 -0.58411592245101929 0.03489559888839722 0.20179396867752075 0.78541076183319092 3.78988555908203125e+02 F ISS
camera 212.58 3.51612 781576832.398 0.69239283372443516 45.32655553839125417 44.90159232421252966 -0.58411580324172974 0.03489561378955841 0.20179399847984314 0.78541076183319092 3.78988525390625000e+02 F ISS
camera 212.764 3.70029 781576832.586 0.69239117799007488 45.32655870541429977 44.90159681218111132 -0.58411592245101929 0.03489565849304199 0.20179401338100433 0.78541082143783569 3.78988494873046875e+02 F ISS
camera 212.941 3.87744 781576832.771 0.69239361291641544 45.32656251733410357 44.90159122145713866 -0.58411592245101929 0.03489568829536438 0.20179396867752075 0.78541082143783569 3.78988494873046875e+02 F ISS
camera 213.129 4.06575 781576832.948 0.69239367769216287 45.32655873099227506 44.90158988035858556 -0.58411586284637451 0.03489565849304199 0.20179399847984314 0.78541082143783569 3.78988525390625000e+02 F ISS
camera 213.307 4.24315 781576833.136 0.69239063378694077 45.32656011237315852 44.90159701270766845 -0.58411586284637451 0.03489549458026886 0.20179402828216553 0.78541082143783569 3.78988494873046875e+02 F ISS
camera 213.499 4.43558 781576833.313 0.69238955403394087 45.32656015082131518 44.90160209655750378 -0.58411586284637451 0.03489542007446289 0.20179399847984314 0.78541082143783569 3.78988464355468750e+02 F ISS
camera 213.683 4.61918 781576833.506 0.69238675848891873 45.32655609749379977 44.90160293238788825 -0.58411580324172974 0.03489527106285095 0.20179404318332672 0.78541082143783569 3.78988464355468750e+02 F ISS
camera 213.853 4.78964 781576833.689 0.69238642365051106 45.32655357949435881 44.90160952538421668 -0.58411574363708496 0.03489528596401215 0.20179402828216553 0.78541094064712524 3.78988433837890625e+02 F ISS
camera 214.04 4.97682 781576833.860 0.69238296449167080 45.32655581382053356 44.90161566644991353 -0.58411574363708496 0.03489534556865692 0.20179405808448792 0.78541088104248047 3.78988433837890625e+02 F ISS
camera 214.219 5.15545 781576834.047 0.69238058149382731 45.32655488465730542 44.90162269646417315 -0.58411568403244019 0.03489515185356140 0.20179405808448792 0.78541094064712524 3.78988403320312500e+02 F ISS
camera 214.389 5.32563 781576834.226 0.69238408882816849 45.32655562649375014 44.90161772012585573 -0.58411574363708496 0.03489519655704498 0.20179405808448792 0.78541100025177002 3.78988433837890625e+02 F ISS
camera 214.579 5.51552 781576834.396 0.69238751360801132 45.32655402666703282 44.90161290762260649 -0.58411574363708496 0.03489516675472260 0.20179405808448792 0.78541088104248047 3.78988433837890625e+02 F ISS
camera 214.757 5.69372 781576834.586 0.69238766692075515 45.32655599776154531 44.90161194061235506 -0.58411568403244019 0.03489530086517334 0.20179404318332672 0.78541088104248047 3.78988433837890625e+02 F ISS
camera 214.951 5.8871 781576834.764 0.69238838806677094 45.32655546644019040 44.90160556066238939 -0.58411580324172974 0.03489533066749573 0.20179402828216553 0.78541088104248047 3.78988464355468750e+02 F ISS
camera 215.131 6.06759 781576834.957 0.69238650239538835 45.32655392197976596 44.90161111877083044 -0.58411568403244019 0.03489531576633453 0.20179405808448792 0.78541094064712524 3.78988433837890625e+02 F ISS
camera 215.305 6.24124 781576835.138 0.69238632426551661 45.32655707176122206 44.90160898688931468 -0.58411580324172974 0.03489531576633453 0.20179404318332672 0.78541088104248047 3.78988433837890625e+02 F ISS
camera 215.491 6.42762 781576835.312 0.69238376330017282 45.32655926026087201 44.90160237585127589 -0.58411580324172974 0.03489531576633453 0.20179405808448792 0.78541088104248047 3.78988464355468750e+02 F ISS
camera 215.671 6.60766 781576835.498 0.69238547652149940 45.32655998309260070 44.90159983189303716 -0.58411586284637451 0.03489547967910767 0.20179398357868195 0.78541088104248047 3.78988464355468750e+02 F ISS
camera 215.849 6.78556 781576835.678 0.69238251256049566 45.32656170635200965 44.90159655188281818 -0.58411586284637451 0.03489546477794647 0.20179404318332672 0.78541082143783569 3.78988464355468750e+02 F ISS
camera 216.043 6.97986 781576835.856 0.69238414904535261 45.32655819108589412 44.90159886489648500 -0.58411586284637451 0.03489544987678528 0.20179399847984314 0.78541082143783569 3.78988494873046875e+02 F ISS
camera 216.225 7.16115 781576836.050 0.69238316853997439 45.32655739870925515 44.90160317388163946 -0.58411574363708496 0.03489546477794647 0.20179402828216553 0.78541088104248047 3.78988464355468750e+02 F ISS
```

**Pull request merged**
