### PR TITLE
update cef and a few calls for it

### PR DESCRIPTION
**Pull request by micahnyc**
There is an issue with the text fields in our gui after this update which needs to be addressed in the -WebGuiFrontend

When using the search fields, sometimes keyevents are sent through to openspace. When using a non search field (such as naming session recording, key events are never sent to openspace. 

In addition, if you check a box or use a slider, then use a search field, then the keyevents are not sent to openspace. 

I'm guessing there is a special behavior on how we have addressed the search fields in react which needs to be updated.

### CODE REVIEW

**Comment by alexanderbock** [comment]
Confirmed happening for me as well.  For me however, every keystroke is sent forwards to OpenSpace in the beginning and then only intermittendly later
 - Search bar in Scene and Settings
 - Search Bar in Focus menu
 - "Star name..." in Exoplanet Systems
 - Float properties when entering numbers directly
 - Seconds / second and Negative Seconds/second in Time Selection window

*not* in:
 - "Name of recording" in Record session
 - Slide name and URL in Screensapace renderables
 - Year/Month/Day/... in Time Selection
 - String Properties

**Comment by alexanderbock** [comment]
Best feature about this, btw is the fact that the UI now works in Debug mode on Windows, too!

**Comment by micahnyc** [comment]
tested and fixed now on macos

**Comment by alexanderbock** [comment]
Not sure if it is related to the CEF but it happens on this branch:
 - The "Play" button in the Record Session panel doesn't work anymore

**Comment by WeirdRubberDuck** [comment]
> Confirmed happening for me as well. For me however, every keystroke is sent forwards to OpenSpace in the beginning and then only intermittendly later
> 
> * Search bar in Scene and Settings
> * Search Bar in Focus menu
> * "Star name..." in Exoplanet Systems
> * Float properties when entering numbers directly
> * Seconds / second and Negative Seconds/second in Time Selection window
> 
> _not_ in:
> 
> * "Name of recording" in Record session
> * Slide name and URL in Screensapace renderables
> * Year/Month/Day/... in Time Selection
> * String Properties

So, this seems to be a problem for our `<Input>` components, but not `<InlineInput>` (such as the date edit the "Select Date" part). Will investigate further

**Comment by WeirdRubberDuck** [comment]
> Not sure if it is related to the CEF but it happens on this branch:
> 
> * The "Play" button in the Record Session panel doesn't work anymore

@alexanderbock seems like this broke as the part of the Lua update. The "sessionrecording.startPlayback" function has been renamed to `startPlaybackDefault`?

**Pull request merged**
